#!/bin/bash
# This script is used to replay the AI's answers to the prompts in the file ai-prompts-curated.txt

keyword=$1
models=$2

if [ -z "$keyword" ]; then
    echo "Usage: ai-replay <keyword> [<models>]"
    exit 1
fi


prompt="$(grep $keyword ai-prompts-curated.txt)"

if [ -z "$prompt" ]; then
  echo -e "\e[31mKeyword '$keyword' not found in ai-prompts-curated.txt\e[0m\n" > /dev/stderr
  exit 1
else
  echo ai \""$prompt"\" $models
       ai \""$prompt"\" $models
fi
